// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const FIELDS=["appearances","starts","minutes","goals","assists"];
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const clean=v=>{const s=String(v??"").trim();return s||null};
const whole=v=>{if(v==null||v==="")return null;const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n)):null};
const norm=v=>String(v||"").trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const reserve=v=>/\b(reserves?|reserve|ii|2|b|u23|u21|academy|youth)\b/.test(norm(v));
const baseClub=v=>norm(v).replace(/\b(fc|football club|reserves?|reserve|ii|2|b|u23|u21|academy|youth)\b/g," ").replace(/\s+/g," ").trim();
function sameClub(a,b,league=""){const x=norm(a),y=norm(b);if(!x||!y)return false;if(x===y||x.includes(y)||y.includes(x))return true;const xb=baseClub(a),yb=baseClub(b);if(!xb||xb!==yb)return false;if(reserve(a)&&reserve(b))return true;return /\b(central league|northern league|southern league|npl|national premier league)\b/.test(norm(league))&&(reserve(a)||reserve(b));}
function sameLeague(a,b){const x=norm(a),y=norm(b);if(!x||!y)return true;if(x===y||x.includes(y)||y.includes(x))return true;const stop=new Set(["the","men","mens","dettol","premier"]),aa=new Set(x.split(" ").filter(t=>t.length>1&&!stop.has(t))),bb=new Set(y.split(" ").filter(t=>t.length>1&&!stop.has(t)));if(!aa.size||!bb.size)return false;const hit=[...aa].filter(t=>bb.has(t)).length;return hit>=2&&hit/Math.min(aa.size,bb.size)>=0.6;}
function currentRow(rows,p){const season=norm(p.current_season_label||String(new Date().getUTCFullYear()));return(rows||[]).filter(r=>(!season||norm(r.season_label)===season)&&sameClub(r.club_name,p.current_club,p.current_league)&&sameLeague(r.league,p.current_league)).sort((a,b)=>FIELDS.filter(f=>b[f]!=null).length-FIELDS.filter(f=>a[f]!=null).length)[0]||null;}
const complete=r=>Boolean(r&&FIELDS.every(f=>r[f]!=null));
const sourceKey=u=>{try{const x=new URL(String(u||""));return`${x.hostname.toLowerCase().replace(/^www\./,"")}${x.pathname.replace(/\/+$/,"")||"/"}`.toLowerCase()}catch{return null}};
const sourceHost=u=>{try{return new URL(String(u||"")).hostname.toLowerCase().replace(/^www\./,"")}catch{return null}};
function outputText(payload){for(const item of payload?.output||[])for(const c of item?.content||[])if(c?.type==="output_text"&&typeof c.text==="string")return c.text;return"";}
function webSources(payload){const out=[];for(const item of payload?.output||[])if(String(item?.type||"").includes("web_search"))for(const s of item?.action?.sources||[]){const url=clean(s?.url);if(url)out.push({url,title:clean(s?.title)||sourceHost(url)||"Web source"});}const seen=new Set();return out.filter(s=>{const k=sourceKey(s.url);if(!k||seen.has(k))return false;seen.add(k);return true;});}
const schema={type:"object",additionalProperties:false,properties:{identity_match:{type:"boolean"},confidence:{type:"number",minimum:0,maximum:1},reason:{type:"string"},row:{type:["object","null"],additionalProperties:false,properties:{season_label:{type:"string"},club_name:{type:"string"},league:{type:["string","null"]},country:{type:["string","null"]},appearances:{type:["integer","null"],minimum:0},starts:{type:["integer","null"],minimum:0},minutes:{type:["integer","null"],minimum:0},goals:{type:["integer","null"],minimum:0},assists:{type:["integer","null"],minimum:0},source_urls:{type:"array",minItems:2,maxItems:8,items:{type:"string"}}},required:["season_label","club_name","league","country","appearances","starts","minutes","goals","assists","source_urls"]}},required:["identity_match","confidence","reason","row"]};

async function research(apiKey,p,existing){
  const model=Deno.env.get("OPENAI_STATS_MODEL")||"gpt-5.6-terra";
  const context={name:[p.first_name,p.last_name].filter(Boolean).join(" "),preferred_name:p.preferred_name,date_of_birth:p.date_of_birth,current_club:p.current_club,current_league:p.current_league,current_country:p.current_country,current_season_label:p.current_season_label||String(new Date().getUTCFullYear()),transfermarkt_url:p.transfermarkt_url,stats_url:p.stats_url,existing_current_row:existing?Object.fromEntries(FIELDS.map(f=>[f,existing[f]])):null};
  const regional=[];if(norm(p.current_league).includes("new south wales"))regional.push("For NPL NSW, prioritise NPL Men's NSW/Football NSW, Sofascore, BeSoccer and Transfermarkt. Search the exact player plus season statistics, then match reports if a field is missing.");if(norm(p.current_league).includes("central league"))regional.push("For New Zealand Central League, prioritise NZ Football/Central Football, Wellington Phoenix, Sofascore, Transfermarkt and Friends of Football NZ.");
  const prompt=["Research the exact player's CURRENT domestic league season statistics using live web search.","Do not invent numbers, infer zero, or mix cups/friendlies with league statistics.","Prove identity from name, DOB, club and supplied profile URLs before accepting data.","The current club may be a parent-club label for a Reserves/II/B/Academy side. Never substitute senior first-team statistics.","Search aggregate season pages first, then official lineups/match reports when needed. Do not stop at identity-only profile pages.","If an existing current row is supplied, treat every non-null figure as trusted. Only fill null fields and never reduce or contradict a trusted figure.","A partial result is acceptable. Unsupported fields must be null.","Require at least two independent website hosts and return only source URLs actually surfaced by web search.",...regional,`Player context: ${JSON.stringify(context)}`,`Current date: ${new Date().toISOString().slice(0,10)}`].join("\n");
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),55000);
  try{
    const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:"medium"},store:false,tools:[{type:"web_search",search_context_size:"high"}],tool_choice:"required",include:["web_search_call.action.sources"],input:[{role:"system",content:[{type:"input_text",text:"You are DJM's conservative football statistics researcher. Recover reliable current-season figures without manufacturing missing data."}]},{role:"user",content:[{type:"input_text",text:prompt}]}],text:{format:{type:"json_schema",name:"djm_current_stats",strict:true,schema}}}),signal:controller.signal});
    const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`OpenAI returned HTTP ${response.status}.`);const raw=outputText(payload);if(!raw)throw new Error("OpenAI returned no structured output.");const plan=JSON.parse(raw);return{ok:Boolean(plan.identity_match&&Number(plan.confidence||0)>=0.85&&plan.row),confidence:Number(plan.confidence||0),reason:clean(plan.reason)||"Research complete",row:plan.row,sources:webSources(payload),model};
  }finally{clearTimeout(timer);}
}
async function writeLog(admin,p,result,model){const now=new Date().toISOString(),src=(result.sources||[]).slice(0,8);await admin.from("player_source_refreshes").insert({player_id:p.id,source:"other",source_url:src[0]?.url||p.stats_url||p.transfermarkt_url||null,status:result.ok?"applied":"failed",requested_at:now,started_at:now,completed_at:now,raw_snapshot:{sources:src,candidate:result.candidate||null},summary:{strategy:"openai_current_web_stats_single_pass",reason:result.reason||null,confidence:result.confidence||0,fields_filled:result.fields_filled||[],research_passes:1,model},error_text:result.ok?null:(result.reason||"AI stats refresh failed"),provider:"openai_web_stats",mode:"preview",facts_discovered:(result.fields_filled||[]).length,review_required:0,accepted_count:(result.fields_filled||[]).length,rejected_count:result.ok?0:1,warning_messages:[],provider_version:model||"unknown",fresh_at:now,capability:"reference_only"});}
async function persist(admin,p,r,existing){
  if(!r?.ok||!r.row)return{ok:false,reason:r?.reason||"Evidence below threshold",confidence:r?.confidence||0,fields_filled:[],sources:r?.sources||[],candidate:r?.row||null};const c=r.row;
  if(!sameClub(c.club_name,p.current_club,p.current_league))return{ok:false,reason:"AI row did not match the current club context.",confidence:r.confidence,fields_filled:[],sources:r.sources,candidate:c};
  const season=norm(p.current_season_label||String(new Date().getUTCFullYear()));if(season&&norm(c.season_label)!==season)return{ok:false,reason:"AI row did not match the current season.",confidence:r.confidence,fields_filled:[],sources:r.sources,candidate:c};
  const allowed=new Map((r.sources||[]).map(s=>[sourceKey(s.url),s]).filter(([k])=>Boolean(k))),verified=[...new Set((c.source_urls||[]).map(clean).filter(Boolean))].map(u=>allowed.get(sourceKey(u))).filter(Boolean),hosts=[...new Set(verified.map(s=>sourceHost(s.url)).filter(Boolean))];if(verified.length<2||hosts.length<2)return{ok:false,reason:"AI evidence did not retain two independent supporting sources.",confidence:r.confidence,fields_filled:[],sources:r.sources,candidate:c};
  const {data:rows,error}=await admin.from("career_entries").select("id,season_label,club_name,league,country,appearances,starts,minutes,goals,assists,notes,source_provider,source_name,source_url,source_reviewed_at,source_synced_at,stats_year").eq("player_id",p.id);if(error)throw error;const exact=currentRow(rows||[],p)||existing,aiOwned=exact&&norm(exact.source_provider).replaceAll(" ","_")==="public_web_evidence",merged={},filled=[];
  for(const f of FIELDS){const oldV=whole(exact?.[f]),newV=whole(c[f]);if(oldV==null&&newV!=null){merged[f]=newV;filled.push(f);}else if(aiOwned&&oldV!=null&&newV!=null)merged[f]=Math.max(oldV,newV);else merged[f]=oldV;}
  const now=new Date().toISOString(),sourceText=verified.map(s=>`${s.title}: ${s.url}`).join(" | ");if(exact?.id&&!aiOwned){if(filled.length){const patch={...Object.fromEntries(FIELDS.map(f=>[f,merged[f]])),notes:[clean(exact.notes),`AI supplemental current-season evidence filled: ${filled.join(", ")}. Sources: ${sourceText}`].filter(Boolean).join("\n"),updated_at:now};const{error:e}=await admin.from("career_entries").update(patch).eq("id",exact.id);if(e)throw e;}return{ok:true,reason:filled.length?"AI safely filled missing current-season fields.":"Verified current row retained; AI found no additional safe fields.",confidence:r.confidence,fields_filled:filled,sources:verified,candidate:c};}
  if(!FIELDS.some(f=>merged[f]!=null))return{ok:false,reason:"AI found no safe numeric statistics.",confidence:r.confidence,fields_filled:[],sources:verified,candidate:c};const payload={player_id:p.id,season_label:clean(c.season_label)||p.current_season_label||String(new Date().getUTCFullYear()),club_name:clean(c.club_name)||p.current_club,league:clean(c.league)||p.current_league,country:clean(c.country)||p.current_country,...Object.fromEntries(FIELDS.map(f=>[f,merged[f]])),notes:`Automatically refreshed current-season public evidence. Sources: ${sourceText}`,source_name:"Cross-checked current public football statistics",source_url:verified[0].url,source_reviewed_at:null,source_provider:"public_web_evidence",source_acceptance_method:"ai_web_current_season_cross_checked_monotonic",source_synced_at:now,stats_year:/^\d{4}$/.test(String(c.season_label||""))?Number(c.season_label):null};if(exact?.id){const{error:e}=await admin.from("career_entries").update(payload).eq("id",exact.id);if(e)throw e;}else{const{error:e}=await admin.from("career_entries").insert(payload);if(e)throw e;}return{ok:true,reason:"AI current-season web evidence saved.",confidence:r.confidence,fields_filled:filled,sources:verified,candidate:c};
}

Deno.serve(async req=>{
  if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),apiKey=Deno.env.get("OPENAI_API_KEY");if(!url||!service)return json({ok:false,error:"Server configuration incomplete"},500);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),supplied=req.headers.get("x-djm-cron")||"",{data:expected}=await admin.rpc("get_push_scheduler_secret");if(!expected||supplied!==expected)return json({ok:false,error:"Unauthorized"},401);const body=await req.json().catch(()=>({})),id=clean(body.player_id);if(!id)return json({ok:false,error:"Player required"},400);
  let p=null,existing=null;
  try{const{data,error}=await admin.from("players").select("id,first_name,last_name,preferred_name,date_of_birth,current_club,current_league,current_country,current_season_label,current_season_start,transfermarkt_url,stats_url").eq("id",id).maybeSingle();if(error)throw error;p=data;if(!p)return json({ok:false,error:"Player not found"},404);if(!p.current_club||["soon","tbc","unknown"].includes(norm(p.current_club)))return json({ok:false,skipped:true,reason:"Current club context missing or placeholder"});const{data:rows,error:re}=await admin.from("career_entries").select("id,season_label,club_name,league,country,appearances,starts,minutes,goals,assists,notes,source_provider,source_name,source_url,source_reviewed_at,source_synced_at,stats_year").eq("player_id",id);if(re)throw re;existing=currentRow(rows||[],p);if(complete(existing))return json({ok:true,skipped:true,current_data:true,current_row:existing});if(!apiKey)return json({ok:false,error:"OPENAI_API_KEY not configured"},500);
    let r;try{r=await research(apiKey,p,existing);}catch(e){const reason=e?.name==="AbortError"||String(e?.message||"").toLowerCase().includes("abort")?"AI web research reached the safe time limit.":(e instanceof Error?e.message:String(e));const failed={ok:false,reason,confidence:0,fields_filled:[],sources:[],candidate:null};await writeLog(admin,p,failed,Deno.env.get("OPENAI_STATS_MODEL")||"gpt-5.6-terra").catch(()=>null);return json({ok:Boolean(existing),current_data:Boolean(existing&&FIELDS.some(f=>existing[f]!=null)),current_row:existing,ai:{used:true,passes:1,timed_out:reason.includes("safe time limit"),reason}});}
    const result=await persist(admin,p,r,existing);await writeLog(admin,p,result,r.model).catch(()=>null);const{data:finalRows}=await admin.from("career_entries").select("id,season_label,club_name,league,appearances,starts,minutes,goals,assists,source_provider,source_synced_at").eq("player_id",id);const current=currentRow(finalRows||[],p);return json({ok:Boolean(result.ok||current),current_data:Boolean(current&&FIELDS.some(f=>current[f]!=null)),current_row:current,ai:{used:true,passes:1,model:r.model,confidence:result.confidence||r.confidence||0,fields_filled:result.fields_filled||[],reason:result.reason,sources:(result.sources||[]).slice(0,8)}});
  }catch(e){const reason=e instanceof Error?e.message:String(e);console.error(JSON.stringify({operation:"ai_player_stats_worker",player_id:id,error:reason}));return json({ok:Boolean(existing),current_data:Boolean(existing&&FIELDS.some(f=>existing[f]!=null)),current_row:existing,error:reason},existing?200:500);}
});
