create or replace function public.djm_universal_search(p_query text,p_limit integer default 30)
returns table(entity_type text,entity_id uuid,title text,subtitle text,detail text,score integer) language sql stable set search_path='' as $$
with q as (select lower(trim(coalesce(p_query,''))) v), results(entity_type,entity_id,title,subtitle,detail,score) as (
 select 'club_contact'::text,p.id,p.full_name,coalesce(e.role_title,'')||case when o.name is not null then ' · '||o.name else '' end,coalesce(cm.value,''),case when lower(p.full_name)=q.v then 100 when lower(p.full_name) like q.v||'%' then 90 else 70 end
 from djm_os.people p cross join q left join lateral (select e.* from djm_os.employments e where e.person_id=p.id and e.is_current order by e.updated_at desc limit 1) e on true left join djm_os.organisations o on o.id=e.organisation_id left join lateral (select value from djm_os.contact_methods c where c.person_id=p.id and c.channel='whatsapp' limit 1) cm on true
 where p.person_type in ('club_contact','contact','club_staff','coach','sporting_director','recruitment') and (q.v='' or lower(coalesce(p.full_name,'')||' '||coalesce(e.role_title,'')||' '||coalesce(o.name,'')||' '||coalesce(cm.value,'')) like '%'||q.v||'%')
 union all select 'club',o.id,o.name,coalesce(o.city,'')||case when o.country is not null then ', '||o.country else '' end,coalesce(o.website_url,''),case when lower(o.name)=q.v then 100 when lower(o.name) like q.v||'%' then 90 else 70 end from djm_os.organisations o cross join q where q.v='' or lower(coalesce(o.name,'')||' '||coalesce(o.city,'')||' '||coalesce(o.country,'')) like '%'||q.v||'%'
 union all select 'signed_player',p.id,coalesce(nullif(p.preferred_name,''),trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,''))),coalesce(p.primary_position,'')||case when p.current_club is not null then ' · '||p.current_club else '' end,coalesce(p.current_country,''),80 from public.players p cross join q where q.v='' or lower(coalesce(p.preferred_name,'')||' '||coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')||' '||coalesce(p.current_club,'')||' '||coalesce(p.primary_position,'')) like '%'||q.v||'%'
 union all select 'recruitment_target',s.id,s.full_name,coalesce(s.primary_position,'')||case when s.current_club is not null then ' · '||s.current_club else '' end,coalesce(s.recruitment_stage,''),75 from djm_os.scouting_prospects s cross join q where s.linked_player_id is null and coalesce(s.availability_status,'')<>'signed_djm' and (q.v='' or lower(coalesce(s.full_name,'')||' '||coalesce(s.current_club,'')||' '||coalesce(s.primary_position,'')||' '||coalesce(s.notes,'')) like '%'||q.v||'%')
 union all select 'deal_room',d.id,d.title,o.name||case when coalesce(nullif(p.preferred_name,''),trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')),sp.full_name) is not null then ' · '||coalesce(nullif(p.preferred_name,''),trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')),sp.full_name) else '' end,coalesce(d.primary_blocker,d.next_decision,d.stage),85 from djm_os.deal_rooms d join djm_os.organisations o on o.id=d.organisation_id left join public.players p on p.id=d.player_id left join djm_os.scouting_prospects sp on sp.id=d.prospect_id cross join q where d.status='active' and (q.v='' or lower(coalesce(d.title,'')||' '||coalesce(o.name,'')||' '||coalesce(p.preferred_name,'')||' '||coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')||' '||coalesce(sp.full_name,'')||' '||coalesce(d.primary_blocker,'')||' '||coalesce(d.next_decision,'')) like '%'||q.v||'%')
 union all select 'memory',m.id,left(m.statement,90),coalesce(m.memory_type,'memory'),coalesce(m.source_label,m.source_kind,''),65 from djm_os.memories m cross join q where m.status='active' and (q.v='' or lower(m.statement) like '%'||q.v||'%')
 union all select 'club_need',n.id,coalesce(n.title,n.position),coalesce(o.name,'')||case when n.position is not null then ' · '||n.position else '' end,coalesce(n.profile_notes,''),70 from djm_os.club_needs n join djm_os.organisations o on o.id=n.organisation_id cross join q where n.status in ('active','open','confirmed') and (q.v='' or lower(coalesce(n.title,'')||' '||coalesce(n.position,'')||' '||coalesce(o.name,'')||' '||coalesce(n.profile_notes,'')) like '%'||q.v||'%')
)
select entity_type,entity_id,title,subtitle,detail,score from results order by score desc,title limit greatest(1,least(coalesce(p_limit,30),100));
$$;
grant execute on function public.djm_universal_search(text,integer) to authenticated;
